### ISSUE TITLE
flake8 quotes plugin

### ISSUE THREAD

**Issue by rizumu** [pinax/pinax-starter-app#1]
A flake8 quoting plugin to enforce the Pinax style guide.

see:
https://github.com/pinax/pinax-checkers/blob/master/pinax/checkers/style.py

**Comment by KatherineMichel** [comment]
Closing issue because ```flake-8-quotes``` was incorporated into latest release. https://github.com/pinax/pinax/wiki/Converting-to-CircleCi-and-Codecov
