### ISSUE TITLE
Define default_app_config in project template

### ISSUE THREAD

**Issue by jacobwegner** [pinax/pinax-starter-app#14]
From the [Django docs](https://docs.djangoproject.com/en/1.7/ref/applications/#configuring-applications):

> If there is no default_app_config, Django uses the base AppConfig class.

**Comment by KatherineMichel** [comment]
Closing issue. This was completed: https://github.com/pinax/pinax-starter-app/commit/f4b2d508276f9f41160b4291f924335c00545116#diff-e196f71444b7270107dd0775b16a69df
