### ISSUE TITLE
Provide instructions in top of README for setting up CircleCI and Codecov

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-starter-app#5]

**Comment by KatherineMichel** [comment]
I personally think this should be part of a larger explanation that people can be referred to about the parts of the pinax-starter-app and how they work. The release guidance can form some basis for this. Any thoughts?

**Comment by KatherineMichel** [comment]
I am going to add a link to global release docs instead. CI and coverage will be explained there are part of release process to onboard possible contributors. This repo will include minimal instructions for getting template up and running.
